### ISSUE TITLE
What is the exact ddl for mot server submission and abstract submission?

### ISSUE THREAD

**Issue by tangjiasheng** [TAO-Dataset/tao#10]

**Comment by achalddave** [comment]
Good question! The deadline is August 16, 11:59PM Anywhere On Earth (AOE, UTC-12). We will mention this on the motchallenge webpage and send out an email with clarification. The manuscript must also be submitted at this time for consideration for honorable mention. We will decide on the prizes on August 17 and contact the winners to prepare short presentations for the workshop on August 23.
