### ISSUE TITLE
Is the number of categories 488?

### ISSUE THREAD

**Issue by dutxubo** [TAO-Dataset/tao#11]
Hello, from the given JSON annotation file, I was only able to parse out 482 categories. However, as mentioned in FAQ, there should be 488 categories. Could you please check the number of categories again? Thank you.

**Comment by achalddave** [comment]
Great question. You're absolutely right - there are only 482 categories. 6 categories were removed from the test set during a final audit / cleaning stage. I've updated the FAQs, and will update our other materials soon (website, slides, etc.) Thanks for bringing this up!
