### ISSUE TITLE
Puzzles on LVIS

### ISSUE THREAD

**Issue by Kewenjing1020** [TAO-Dataset/tao#12]
Hi, as I know is that TAO contains sequences from 7 datasets, doesn't includes LVIS. But, why there's {train,validation}.json and {train,validation}_with_freeform.json in the annotation?  Which one should I use for training? What's the relation between LVIS and TAO? 

Besides, as you have mentioned, we can train the detector on LVIS-v0.5 and COCO. From the official website of LVIS, only v1..0 is accessible now. Could you please share the download link of LVIS-v0.5, or the mapping relation from v1.0 to v0.5?

**Comment by achalddave** [comment]
Thanks for the great questions!

- Why is there {train,validation}.json and {train,validation}_with_freeform.json? As noted in our paper, TAO contains objects labeled with LVIS categories, as well as free-form text categories. The {train,validation}.json files contain only the annotations for LVIS categories, while {train,validation}_with_freeform.json contain free-form text categories as well. You may use either of these for training. For the ECCV '20 challenge, we will only evaluate on the LVIS categories.

- LVIS v0.5: Yes, good point. I've uploaded the LVIS v0.5 annotations here: https://drive.google.com/drive/folders/1IHDbIvx0BQcj4BHkFLnEUwX4KOtaabTd?usp=sharing (alternative links [v0.5 train](https://cdn3.vision.in.tum.de/~tao/lvis-v0.5/lvis_v0.5_train.json), [v0.5 val](https://cdn3.vision.in.tum.de/~tao/lvis-v0.5/lvis_v0.5_val.json)).
