### ISSUE TITLE
unexpected result after run detector

### ISSUE THREAD

**Issue by Kewenjing1020** [TAO-Dataset/tao#13]
Hi, i tried to run the released detector with following script:
```
 DETECTRON_MODEL=/proj/rdi/staff/wenjingk/MOT/TAO/detector-r101-fpn-1x-lvis-coco
 TAO_ROOT=/group/dphi_gpu_scratch/wenjingk/TAO/frames/
 python scripts/detectors/detectron2_infer.py \
     --gpus 0 1 2 3 \
     --root $TAO_ROOT/val \
     --output ./detectron2_output/val \
     --config $DETECTRON_MODEL/config.yaml \
     --opts MODEL.WEIGHTS $DETECTRON_MODEL/model_final.pth

```
and i get an unexpected output: 
`ustaw zmienną środowiskową MILION_ROOT! (np. /home/milion, najlepiej w .bashrc)`

Do you know what's the problem?

**Comment by Kewenjing1020** [comment]
The problem is solved. It has two causes:
1. script_utils is not installed.
2. some files don't allow execution. so I changed file permissions.

**Comment by John-Yao** [comment]
Hi, I also met the issue.
I try to changed file permission and install the package. But I could not figure out.
@achalddave Could you provide some helps! Thanks.

**Comment by John-Yao** [comment]
I reinstall script_utils by
pip install git+https://github.com/achalddave/python-script-utils.git#egg=script_utils
It run well!
