### ISSUE TITLE
About the factsheet template

### ISSUE THREAD

**Issue by John-Yao** [TAO-Dataset/tao#14]
Hi, 
Are there any requirements for report?
Could you provide the template(.tex)? Thanks!

**Comment by achalddave** [comment]
We do not have a strict requirement on the template, as long as it is typeset with LaTeX and conveys the details of the submission. We would recommend (but do not require) the CVPR template (http://cvpr2020.thecvf.com/sites/default/files/2019-09/cvpr2020AuthorKit.zip) as it is denser than the ECCV one.

**Comment by John-Yao** [comment]
Thanks!
