### ISSUE TITLE
Confused about annotation and submission

### ISSUE THREAD

**Issue by John-Yao** [TAO-Dataset/tao#15]
Hi, @achalddave 
We check the provided json in annotations folder and noticed that the some different between json and images in frames.

Here are some difference between images folder and annotation:

In frames/train/ there are 507 videos -> In train.json only 500 videos
In frames/train/ there are 534593 images -> In train.json only 18274 images
In train.json frame_idx count from any number and increase by  30.

Here are some question about submission:
Whether only  the frame occur in train/valid/test json need to be submitted?

**Comment by achalddave** [comment]
Only the frames in the json are evaluated and only annotations for those
frames need to be submitted. The annotation and evaluation is at 1 frame
per second, so the number of annotated frames is much less than the total
number or frames, as you noted.

**Comment by John-Yao** [comment]
Thanks for the clarification!
I also noticed that it is difficult to infer  the frame idx by filename of images.
In scripts/trackers/sort/track.py, function natsorted is used to sorted  the predicted pkl files and performance tracking on sorted boxes.
Could we infer the frame index by sorted pkl files?
Thanks!

**Comment by achalddave** [comment]
Yup, you should be able to use this to infer the frame index! It's what I did for the baselines. For the annotated frames, there is also a "frame_index" field in the annotations json which can be used to sort frames (note that the absolute value of the frame_index field is not useful, as it corresponds to the index in the original video, but the relative values are useful).
