### ISSUE TITLE
Some videos of the test set are not included in submission?

### ISSUE THREAD

**Issue by fandulu** [TAO-Dataset/tao#16]
Hi, I just checked 'test_without_annotations.json' and find that it does not contain some videos of the given test set, e.g.,
ArgoVerse
test/ArgoVerse/side_right_29789600-2979-2979-2979-429790834688
test/ArgoVerse/side_right_49d66e75-3ce6-316b-b589-f659c7ef5e6d
test/ArgoVerse/side_right_55592286-d867-3c00-8db0-972810eab6d8
BDD
test/BDD/b26f9b1e-09c56a3c
...
Should I ignore them in the submission?

**Comment by achalddave** [comment]
Yes, these videos can be ignored.
