### ISSUE TITLE
Using non-keyframe in testing

### ISSUE THREAD

**Issue by xingyizhou** [TAO-Dataset/tao#17]
Hi Achal,
  Following https://github.com/TAO-Dataset/tao/issues/15, I just realized the high-framerate version of the test set is available. This comes to a critical question: is using the non-keyframe in the test set allowed in the challenge? The baseline provided in the paper does not use the intermediate frames, right? This makes a huge difference because tracking in 30FPS is way easier than tracking in 1FPS.  Can you make it absolutely clear?

Best,
Xingyi

**Comment by achalddave** [comment]
Yes, using the unlabeled frames (i.e., the original frames / "non-keyframe"s as you said) in the test set is definitely allowed. Sorry -- I didn't realize this was unclear! The released baselines and the baselines in the paper all use these unlabeled/non-keyframe frames as well. Indeed, tracking is super hard without using them.

**Comment by xingyizhou** [comment]
I see. Thanks for the clarification!
