### ISSUE TITLE
Is the pred_classes in detection model consistant with category id in tracking?

### ISSUE THREAD

**Issue by Kewenjing1020** [TAO-Dataset/tao#19]
Hi, can i assign the **pred_class** in detection result to **category_id** in track result? Do I need to do any mapping?

I have tried with the released detection model, and i found that person are predicted as label "804". But as i have checked in the category list, 804 represents persimmon and 805 represents person.

**Comment by achalddave** [comment]
If you are using the LVIS v0.5 annotations, you should just need to add 1 to the output of the pred classes. Detectron2 training subtracts 1 from the LVIS category ids to make the categories 0-indexed (https://github.com/facebookresearch/detectron2/blob/09c4fa90bb9266214e2869e58eb462af0b99c1f1/detectron2/data/datasets/lvis.py#L134), which we undo in the sample tracker here (https://github.com/TAO-Dataset/tao/blob/4b191605f2ffbdbe4aea9f66ce02f7dec5e616e9/scripts/trackers/sort/track.py#L115-L118). Hope that helps!
