### ISSUE TITLE
Why is it a bug?

### ISSUE THREAD

**Issue by fanq15** [TAO-Dataset/tao#21]
https://github.com/TAO-Dataset/tao/blob/4b191605f2ffbdbe4aea9f66ce02f7dec5e616e9/tao/toolkit/tao/tao.py#L102

**Comment by achalddave** [comment]
Hm, could you expand? Did this assertion fire for you when evaluating? This check should never fire. 

Background: In TAO, we merged a small number of LVIS categories together as they have very similar definitions and labelers were not able to tell them apart. I will document this in the evaluation soon. The if statement you linked just ensures that this merging is properly indicated in the json file.

**Comment by fanq15** [comment]
I use TAO api to process my own dataset. Should I ignore it on my own dataset if I do not need to merge categories?

**Comment by achalddave** [comment]
Yup! Feel free to delete that line. You can also delete / comment out these lines: https://github.com/TAO-Dataset/tao/blob/4b191605f2ffbdbe4aea9f66ce02f7dec5e616e9/tao/toolkit/tao/tao.py#L113-L116

Let me know if you run into other problems by filing a new issue! The TAO api should be usable for other datasets, but there are likely some small issues you can run into. One major note is that the TAO api expects a federated dataset, so make sure to set up "neg_category_ids" and "not_exhaustive_category_ids" correctly in your annotations JSON.
