### ISSUE TITLE
MOTA evaluation code

### ISSUE THREAD

**Issue by dmckee5** [TAO-Dataset/tao#22]
Hello, I noticed the evaluation_mota module is missing. Will this code be added soon as well? 

Thanks!
Daniel

```
ModuleNotFoundError: No module named 'tao.utils.evaluation_mota'
```

**Comment by achalddave** [comment]
Thanks for pointing this out. I'll add this soon, hopefully tomorrow.

**Comment by achalddave** [comment]
Just pushed: https://github.com/TAO-Dataset/tao/blob/master/tao/utils/evaluation_mota.py
