### ISSUE TITLE
Symlinks broken in annotations/video-lists

### ISSUE THREAD

**Issue by jpuigcerver** [TAO-Dataset/tao#26]
Hi, 

I downloaded the annotations v1.1 file from https://github.com/TAO-Dataset/annotations/archive/v1.1.tar.gz. All symlinks the in the video-lists directory are broken, including the README.md.

**Comment by achalddave** [comment]
This was fixed in v1.2, please download those annotations instead: https://github.com/TAO-Dataset/annotations/archive/v1.2.tar.gz

I've updated the https://github.com/TAO-Dataset/tao/blob/master/scripts/download/download_annotations.py script to download v1.2 now as well.
