### ISSUE TITLE
imagenetvid iou

### ISSUE THREAD

**Issue by hf1995** [TAO-Dataset/tao#31]
**_num_total_** has duplicate statistics. I wonder if line 67 https://github.com/TAO-Dataset/tao/blob/3282f29212a40ddc3785cd4d4cd311c6b7b8e084/tao/toolkit/tao/eval.py#L67 should be deleted, and **_num_total_** can be calculated on line 70 https://github.com/TAO-Dataset/tao/blob/3282f29212a40ddc3785cd4d4cd311c6b7b8e084/tao/toolkit/tao/eval.py#L70.

**Comment by achalddave** [comment]
Great catch, yes! If you could submit a PR, happy to merge. Otherwise, I'll fix in the next release / update. I'll leave this issue open until then.
