### ISSUE TITLE
AVA and HACS datasets not found 

### ISSUE THREAD

**Issue by brjathu** [TAO-Dataset/tao#32]
Hi, I followed the same instructions and downloaded the dataset from the officail website. However AVA and HACS are missing in the train, val, test folders. The verify.py code also reports these files are missing. 
AVA         : FAILED 𐄂𐄂𐄂
HACS        : FAILED 𐄂𐄂𐄂

**Comment by achalddave** [comment]
Sorry about that. To clarify, you downloaded the AVA and HACS datasets from https://motchallenge.net/tao_download.php and followed the second step there? This will require logging into the MOT challenge website: https://motchallenge.net/tao_download_secure.php

**Comment by brjathu** [comment]
Thank you very much.
