### ISSUE TITLE
How to download AVA and HACS datasets ?

### ISSUE THREAD

**Issue by CarlHuangNuc** [TAO-Dataset/tao#33]
Hi,
    follow guideline, we need to register MOT Challenge account.

    But i can not get approved from the website for long time.

     Is there any other way to download AVA and HACS datasets?

**Comment by shanpoyang654** [comment]
> Hi, follow guideline, we need to register MOT Challenge account.
> 
> ```
> But i can not get approved from the website for long time.
> 
>  Is there any other way to download AVA and HACS datasets?
> ```

the same question!  Have you downloaded AVA and HACS datasets?
If you have downloaded successfully, could you please give me one copy?

**Comment by achalddave** [comment]
Hi - are you still not approved? This should happen on a frequent (~daily) basis. Please email info@motchallenge.net if you are still having issues. Unfortunately, the TAO authors don't have direct control of the MOT Challenge website.
