### ISSUE TITLE
[Request] I can't get the approval to download TAO HACS&AVA datasets from MOT challenge team.

### ISSUE THREAD

**Issue by clownrat6** [TAO-Dataset/tao#34]
The MOT challenge team doesn't provide any feedback for my request e-mail. Is there any solution?

**Comment by achalddave** [comment]
Hi - are you still not approved? This should happen on a frequent (~daily) basis. Please email [info@motchallenge.net](mailto:info@motchallenge.net) if you are still having issues. Unfortunately, the TAO authors don't have direct control of the MOT Challenge website.

**Comment by achalddave** [comment]
Sorry, I just re-read your message. When did you contact them, and what email ids did you contact? Could you please email me at achalddave@gmail.com and I'll try to contact some people directly.

**Comment by aitor-martinez-seras** [comment]
Hi there! The problem still happening, I'm not receiving any email to continue with my register. I have emailed [info@motchallenge.net](mailto:info@motchallenge.net), but I'm not getting any response. Could anyone help me?

**Comment by aitor-martinez-seras** [comment]
Solved, received the email!
Thanks!

**Comment by zsz00** [comment]
The problem still happening, I'm not receiving any email to continue with my register. I have emailed [info@motchallenge.net](mailto:info@motchallenge.net), but I'm not getting any response. Could anyone help me?

**Comment by achalddave** [comment]
The dataset is now available on HuggingFace via our follow-up work TAO-Amodal, so you should no longer need to access MOTChallenge! https://huggingface.co/datasets/chengyenhsieh/TAO-Amodal
