### ISSUE TITLE
[ERROR] The download quota for this file has been exceeded

### ISSUE THREAD

**Issue by gongbudaizhe** [TAO-Dataset/tao#5]
When I download the file via gdrive, the error message is:

> The download quota for this file has been exceeded

When I download the file via web browser, the error message is:
> Sorry, you can't view or download this file at this time.

> Too many users have viewed or downloaded this file recently. Please try accessing the file again later. If the file that you are trying to access is particularly large or is shared with many people, it may take up to 24 hours to be able to view or download the file. If you still can't access a file after 24 hours, contact your domain administrator.

**Comment by achalddave** [comment]
Thanks for the report! Sorry for the trouble. We are actively looking into sharing the data elsewhere... Will update here tomorrow.

**Comment by yizhou-wang** [comment]
Hi @achalddave, this error also occurs for downloading the pretrained detection model here: https://drive.google.com/file/d/13BdXSQDqK0t-LrF2CrwJtT9lFc48u83H/view?usp=sharing

**Comment by tarashakhurana** [comment]
@gongbudaizhe The dataset has now been temporarily hosted on the TUM servers. Please `wget` from the following links
```bash
https://cdn3.vision.in.tum.de/~tao/train.zip
https://cdn3.vision.in.tum.de/~tao/val.zip
https://cdn3.vision.in.tum.de/~tao/test.zip
```
For HACS/AVA videos, you still have to submit the form and we will give you a new link. This information has also been added to the download doc. 

@yizhou-wang working on the pretrained detection model.

**Comment by tarashakhurana** [comment]
@yizhou-wang The pretrained detection model is now alternatively available [here](https://cdn3.vision.in.tum.de/~tao/baselines/detector-r50-fpn-1x-lvis-coco.zip).
