### ISSUE TITLE
Need to update annotations-1.0 to annotations-1.1 in download_annotations.py

### ISSUE THREAD

**Issue by jvlmdr** [TAO-Dataset/tao#6]
Running `download_annotations.py` gave me the error
```python
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/disks/disk-1/tao/original/annotations-1.0' -> '/mnt/disks/disk-1/tao/original/annotations'
```
I think it is necessary to update this line:
https://github.com/TAO-Dataset/tao/blob/f908408697205d96d5508f6f9c21e17409482da7/scripts/download/download_annotations.py#L60

**Comment by achalddave** [comment]
Oops, thanks! Fixed.

**Comment by shubham-goel** [comment]
I think it needs to be updated to 1.2 now!

**Comment by achalddave** [comment]
Thanks :) Fixed.
