### ISSUE TITLE
The submission need follow any sequence?

### ISSUE THREAD

**Issue by fandulu** [TAO-Dataset/tao#9]
Could I ask a question? The baseline Tracker seems to generate txt files and we need to merge them into a json file, do we need to follow any sequence?

**Comment by achalddave** [comment]
Hm, which tracker generates text files? The instructions here should generate a json file, let me know if that's not the case: https://github.com/TAO-Dataset/tao/blob/master/docs/trackers.md

But to answer your specific question: the order of the results in the JSON file does not matter.

**Comment by fandulu** [comment]
Thanks for replying. May I ask what is the file for 
--annotations $TAO_ROOT/annotations/train.json \ in https://github.com/TAO-Dataset/tao/blob/master/docs/trackers.md
when change to test.json, how can I create it?

**Comment by achalddave** [comment]
You should be able to replace it with
`$TAO_ROOT/annotations/test_without_annotations.json`. Please let me know
if that doesn’t work!
